title: HasturBoss's Blob
email: hasturboss@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  The road is long and long, and I will search up and down.
  Silence, silence! Unless we burst out, we shall perish in this silence.
baseurl: "/Hastur" # the subpath of your site, e.g. /blog
url: "https://hasturboss.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username: hasturboss
twitter_username: microsoft

# Build settings
plugins:
  - jekyll-feed

google_analytics: G-VEYWXV2XQQ
