title: HasturBoss's Blob
author:
  name: Hastur Boss
  email: hasturboss@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  The road is long and long, and I will search up and down.
  Human beings are powerful and weak, humble and sublime, perceptive and often blind.
  (hasturboss)
baseurl: "/Hastur" # the subpath of your site, e.g. /blog
url: "https://hasturboss.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# social_links:
#   - { platform: devto,          user_url: "https://dev.to/jekyll" }
#   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
#   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
#   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
#   - { platform: google,         user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
#   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
#   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
#   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
#   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
#   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
#   - { platform: telegram,       user_url: "https://t.me/jekyll" }
#   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
#   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
minima:
  skin: default
  social_links:
    - { platform: github,  user_url: "https://github.com/HasturBoss/Hastur" }
    - { platform: youtube,  user_url: "https://www.youtube.com/@user-yor" }
    - { platform: facebook,  user_url: "https://www.facebook.com/profile.php?id=100051853814324" }

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md

google_analytics: G-VEYWXV2XQQ
